def see(a,b):  
    if a=='1':  
        if b=='1':return '19'  
        elif b=='2':return '57'  
        elif b=='3':return '58'  
        elif b=='4':return '53'  
        elif b=='5':return '51'  
        elif b=='6':return '12'  
        elif b=='7':return '56'  
        elif b=='8':return '14'  
        elif b=='9':return '55'  
        else:return 'error'  
    elif a=='2':  
        if b=='1':return    '57'  
        elif b=='2':return '28'  
        elif b=='3':return '59'  
        elif b=='4':return '91'  
        elif b=='5':return '52'  
        elif b=='6':return '73'  
        elif b=='7':return '74'  
        elif b=='8':return '55'  
        elif b=='9':return '96'  
        else:return 'error'  
    elif a=='3':  
        if b=='1':return '58'  
        elif b=='2':return '59'  
        elif b=='3':return '37'  
        elif b=='4':return '32'  
        elif b=='5':return '53'  
        elif b=='6':return '51'  
        elif b=='7':return '55'  
        elif b=='8':return '36'  
        elif b=='9':return '54'  
        else:return 'error'  
    elif a=='4':  
        if b=='1':return '53'  
        elif b=='2':return '91'  
        elif b=='3':return '32'  
        elif b=='4':return '46'  
        elif b=='5':return '54'  
        elif b=='6':return '55'  
        elif b=='7':return '59'  
        elif b=='8':return '37'  
        elif b=='9':return '98'  
        else:return 'error'  
    elif a=='5':  
        if b=='1':return '51'  
        elif b=='2':return '52'  
        elif b=='3':return '53'  
        elif b=='4':return '54'  
        elif b=='5':return '55'  
        elif b=='6':return '56'  
        elif b=='7':return '57'  
        elif b=='8':return '58'  
        elif b=='9':return '59'  
        else:return 'error'  
    elif a=='6':  
        if b=='1':return '12'  
        elif b=='2':return '73'  
        elif b=='3':return '51'  
        elif b=='4':return '55'  
        elif b=='5':return '56'  
        elif b=='6':return '64'  
        elif b=='7':return '78'  
        elif b=='8':return '19'  
        elif b=='9':return '57'  
        else:return 'error'  
    elif a=='7':  
        if b=='1':return '56'  
        elif b=='2':return '74'  
        elif b=='3':return '55'  
        elif b=='4':return '59'  
        elif b=='5':return '57'  
        elif b=='6':return '78'  
        elif b=='7':return '73'  
        elif b=='8':return '51'  
        elif b=='9':return '52'  
        else:return 'error'  
    elif a=='8':  
        if b=='1':return '14'  
        elif b=='2':return '55'  
        elif b=='3':return '36'  
        elif b=='4':return '37'  
        elif b=='5':return '58'  
        elif b=='6':return '19'  
        elif b=='7':return '51'  
        elif b=='8':return '82'  
        elif b=='9':return '53'  
        else:return 'error'  
    elif a=='9':  
        if b=='1':return '55'  
        elif b=='2':return '96'  
        elif b=='3':return '54'  
        elif b=='4':return '98'  
        elif b=='5':return '59'  
        elif b=='6':return '57'  
        elif b=='7':return '52'  
        elif b=='8':return '53'  
        elif b=='9':return '91'  
        else:return 'error'  
    else:return 'error'  
