def look(a,b):  
    if a=='1':  
        if b=='1':return '51'  
        elif b=='2':return '52'  
        elif b=='3':return '53'  
        elif b=='4':return '54'  
        elif b=='5':return '55'  
        elif b=='6':return '56'  
        elif b=='7':return '57'  
        elif b=='8':return '58'  
        elif b=='9':return '59'  
        else:return 'error'  
    elif a=='2':  
        if b=='1':return '52'  
        elif b=='2':return '37'  
        elif b=='3':return '56'  
        elif b=='4':return '19'  
        elif b=='5':return '55'  
        elif b=='6':return '91'  
        elif b=='7':return '54'  
        elif b=='8':return '73'  
        elif b=='9':return '58'  
        else:return 'error'  
    elif a=='3':  
        if b=='1':return '53'  
        elif b=='2':return '56'  
        elif b=='3':return '59'  
        elif b=='4':return '52'  
        elif b=='5':return '55'  
        elif b=='6':return '58'  
        elif b=='7':return '51'  
        elif b=='8':return '54'  
        elif b=='9':return '57'  
        else:return 'error'  
    elif a=='4':  
        if b=='1':return '54'  
        elif b=='2':return '19'  
        elif b=='3':return '52'  
        elif b=='4':return '73'  
        elif b=='5':return '55'  
        elif b=='6':return '37'  
        elif b=='7':return '58'  
        elif b=='8':return '91'  
        elif b=='9':return '56'  
        else:return 'error'  
    elif a=='5':  
        return '55'  
    elif a=='6':  
        if b=='1':return '56'  
        elif b=='2':return '91'  
        elif b=='3':return '58'  
        elif b=='4':return '37'  
        elif b=='5':return '55'  
        elif b=='6':return '73'  
        elif b=='7':return '52'  
        elif b=='8':return '19'  
        elif b=='9':return '54'  
        else:return 'error'  
    elif a=='7':  
        if b=='1':return '57'  
        elif b=='2':return '54'  
        elif b=='3':return '51'  
        elif b=='4':return '58'  
        elif b=='5':return '55'  
        elif b=='6':return '52'  
        elif b=='7':return '59'  
        elif b=='8':return '56'  
        elif b=='9':return '53'  
        else:return 'error'  
    elif a=='8':  
        if b=='1':return '58'  
        elif b=='2':return '73'  
        elif b=='3':return '54'  
        elif b=='4':return '91'  
        elif b=='5':return '55'  
        elif b=='6':return '19'  
        elif b=='7':return '56'  
        elif b=='8':return '37'  
        elif b=='9':return '52'  
        else:return 'error'  
    elif a=='9':  
        if b=='1':return '59'  
        elif b=='2':return '58'  
        elif b=='3':return '57'  
        elif b=='4':return '56'  
        elif b=='5':return '55'  
        elif b=='6':return '54'  
        elif b=='7':return '53'  
        elif b=='8':return '52'  
        elif b=='9':return '51'  
        else:return 'error'  
    else:return 'error'  
